#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi

echo 'Waiting for MySQL IS STARTED...'

if [ ! -f ".env" ]; then
	echo "Creating .env file for env $APP_ENV"
	cp .env.example .env
else
	echo "Using existing .env file"
fi
# Wait for MySQL to be ready
# until mysqladmin ping -hmysql -u"${DB_USERNAME}" -p"${DB_PASSWORD}"; do
#     echo 'Waiting for MySQL to be ready...'
#     sleep 1
# done

# echo 'Waiting for MySQL IS DONE...'

# # Run the original entry point command (passed as arguments)
# exec "php artisan migrate"
